package models

import (
	"database/sql"
	"time"
)

type POutd struct {
	AmendsAmount            sql.NullFloat64 `gorm:"column:AmendsAmount" json:"AmendsAmount"`
	Amount                  sql.NullFloat64 `gorm:"column:Amount" json:"Amount"`
	Attribute1              sql.NullString  `gorm:"column:Attribute1" json:"Attribute1"`
	Attribute2              sql.NullString  `gorm:"column:Attribute2" json:"Attribute2"`
	Attribute3              sql.NullString  `gorm:"column:Attribute3" json:"Attribute3"`
	Attribute4              sql.NullString  `gorm:"column:Attribute4" json:"Attribute4"`
	Attribute5              sql.NullString  `gorm:"column:Attribute5" json:"Attribute5"`
	Attribute6              sql.NullString  `gorm:"column:Attribute6" json:"Attribute6"`
	Attribute7              sql.NullString  `gorm:"column:Attribute7" json:"Attribute7"`
	Attribute8              sql.NullString  `gorm:"column:Attribute8" json:"Attribute8"`
	BHAmountD               sql.NullFloat64 `gorm:"column:BHAmountD" json:"BHAmountD"`
	BHDateD                 time.Time       `gorm:"column:BHDateD" json:"BHDateD"`
	BHPayeeD                sql.NullString  `gorm:"column:BHPayeeD" json:"BHPayeeD"`
	BHPercentD              sql.NullFloat64 `gorm:"column:BHPercentD" json:"BHPercentD"`
	Bin                     string          `gorm:"column:Bin" json:"Bin"`
	BonusAmount             sql.NullFloat64 `gorm:"column:BonusAmount" json:"BonusAmount"`
	Box                     sql.NullString  `gorm:"column:Box" json:"Box"`
	BoxNo                   sql.NullString  `gorm:"column:BoxNo" json:"BoxNo"`
	Boxes                   sql.NullInt64   `gorm:"column:Boxes" json:"Boxes"`
	CIWPCode                sql.NullString  `gorm:"column:CIWPCode" json:"CIWPCode"`
	ChargeAmount            sql.NullFloat64 `gorm:"column:ChargeAmount" json:"ChargeAmount"`
	ComNo                   sql.NullString  `gorm:"column:ComNo" json:"ComNo"`
	CostPrice               sql.NullFloat64 `gorm:"column:CostPrice" json:"CostPrice"`
	DeliveryCode            sql.NullString  `gorm:"column:DeliveryCode" json:"DeliveryCode"`
	DeliveryName            sql.NullString  `gorm:"column:DeliveryName" json:"DeliveryName"`
	DepartmentD             sql.NullString  `gorm:"column:DepartmentD" json:"DepartmentD"`
	DiscPrice               sql.NullFloat64 `gorm:"column:DiscPrice" json:"DiscPrice"`
	DiscRate2               sql.NullFloat64 `gorm:"column:DiscRate2" json:"DiscRate2"`
	DiscRate3               sql.NullFloat64 `gorm:"column:DiscRate3" json:"DiscRate3"`
	DiscRate4               sql.NullFloat64 `gorm:"column:DiscRate4" json:"DiscRate4"`
	DiscountRate            sql.NullFloat64 `gorm:"column:DiscountRate" json:"DiscountRate"`
	EnglishName             sql.NullString  `gorm:"column:EnglishName" json:"EnglishName"`
	FAccType                sql.NullString  `gorm:"column:FAccType" json:"FAccType"`
	FCode                   sql.NullString  `gorm:"column:FCode" json:"FCode"`
	FInvoiceType            sql.NullString  `gorm:"column:FInvoiceType" json:"FInvoiceType"`
	FOBCurrency             sql.NullString  `gorm:"column:FOBCurrency" json:"FOBCurrency"`
	FOBPrice                sql.NullFloat64 `gorm:"column:FOBPrice" json:"FOBPrice"`
	FOBRate                 sql.NullFloat64 `gorm:"column:FOBRate" json:"FOBRate"`
	FalseAttribute2         sql.NullString  `gorm:"column:FalseAttribute2" json:"FalseAttribute2"`
	FalseAttribute3         sql.NullString  `gorm:"column:FalseAttribute3" json:"FalseAttribute3"`
	FalseItemCode           sql.NullString  `gorm:"column:FalseItemCode" json:"FalseItemCode"`
	FalseItemName           sql.NullString  `gorm:"column:FalseItemName" json:"FalseItemName"`
	FalsePrice              sql.NullFloat64 `gorm:"column:FalsePrice" json:"FalsePrice"`
	FastInCode              sql.NullString  `gorm:"column:FastInCode" json:"FastInCode"`
	GroupNo                 sql.NullString  `gorm:"column:GroupNo" json:"GroupNo"`
	GroupWareCode           sql.NullString  `gorm:"column:GroupWareCode" json:"GroupWareCode"`
	IndexID                 sql.NullInt64   `gorm:"column:IndexID" json:"IndexID"`
	Integral                sql.NullFloat64 `gorm:"column:Integral" json:"Integral"`
	IntegralProportion      sql.NullFloat64 `gorm:"column:IntegralProportion" json:"IntegralProportion"`
	IsCanIntegral           sql.NullInt64   `gorm:"column:IsCanIntegral" json:"IsCanIntegral"`
	IsCheckPLC              sql.NullInt64   `gorm:"column:IsCheckPLC" json:"IsCheckPLC"`
	IsCheckPLL              sql.NullInt64   `gorm:"column:IsCheckPLL" json:"IsCheckPLL"`
	IsCheckPLT              sql.NullInt64   `gorm:"column:IsCheckPLT" json:"IsCheckPLT"`
	IsFast                  sql.NullInt64   `gorm:"column:IsFast" json:"IsFast"`
	IsGroupWare             sql.NullInt64   `gorm:"column:IsGroupWare" json:"IsGroupWare"`
	IsItemPromotion         sql.NullInt64   `gorm:"column:IsItemPromotion" json:"IsItemPromotion"`
	IsMemberSet             sql.NullInt64   `gorm:"column:IsMemberSet" json:"IsMemberSet"`
	IsNegativeOut           sql.NullInt64   `gorm:"column:IsNegativeOut" json:"IsNegativeOut"`
	IsPresent               sql.NullInt64   `gorm:"column:IsPresent" json:"IsPresent"`
	IsSalesPromotion        sql.NullInt64   `gorm:"column:IsSalesPromotion" json:"IsSalesPromotion"`
	ItemCode                sql.NullString  `gorm:"column:ItemCode" json:"ItemCode"`
	ItemName                sql.NullString  `gorm:"column:ItemName" json:"ItemName"`
	ItemRemarks             sql.NullString  `gorm:"column:ItemRemarks" json:"ItemRemarks"`
	JobType                 sql.NullString  `gorm:"column:JobType" json:"JobType"`
	LastOutPrice            sql.NullFloat64 `gorm:"column:LastOutPrice" json:"LastOutPrice"`
	Location                string          `gorm:"column:Location" json:"Location"`
	MainWorker              sql.NullString  `gorm:"column:MainWorker" json:"MainWorker"`
	MemberSetDiffAmount     float64         `gorm:"column:MemberSetDiffAmount" json:"MemberSetDiffAmount"`
	MemberSetDiffPrice      float64         `gorm:"column:MemberSetDiffPrice" json:"MemberSetDiffPrice"`
	MemberSetItemCode       string          `gorm:"column:MemberSetItemCode" json:"MemberSetItemCode"`
	MemberSetPrice          float64         `gorm:"column:MemberSetPrice" json:"MemberSetPrice"`
	MemberSetRemark         string          `gorm:"column:MemberSetRemark" json:"MemberSetRemark"`
	MemberSetSalesCode      sql.NullString  `gorm:"column:MemberSetSalesCode" json:"MemberSetSalesCode"`
	NeedIntegral            sql.NullFloat64 `gorm:"column:NeedIntegral" json:"NeedIntegral"`
	NoTaxCostPrice          sql.NullFloat64 `gorm:"column:NoTaxCostPrice" json:"NoTaxCostPrice"`
	OldPrice                sql.NullFloat64 `gorm:"column:OldPrice" json:"OldPrice"`
	OldQty                  sql.NullFloat64 `gorm:"column:OldQty" json:"OldQty"`
	OrderID                 sql.NullInt64   `gorm:"column:OrderID" json:"OrderID"`
	OutFlag1                sql.NullInt64   `gorm:"column:OutFlag1" json:"OutFlag1"`
	OutFlag2                sql.NullInt64   `gorm:"column:OutFlag2" json:"OutFlag2"`
	OutFlag3                sql.NullInt64   `gorm:"column:OutFlag3" json:"OutFlag3"`
	OutOrderQty             sql.NullFloat64 `gorm:"column:OutOrderQty" json:"OutOrderQty"`
	OutPriceAmount          sql.NullFloat64 `gorm:"column:OutPriceAmount" json:"OutPriceAmount"`
	OutRemarks              sql.NullString  `gorm:"column:OutRemarks" json:"OutRemarks"`
	PBackHanderCodeD        sql.NullString  `gorm:"column:PBackHanderCodeD" json:"PBackHanderCodeD"`
	PCOIndexID              sql.NullInt64   `gorm:"column:PCOIndexID" json:"PCOIndexID"`
	PCS                     sql.NullInt64   `gorm:"column:PCS" json:"PCS"`
	PCustomerOrderCode      sql.NullString  `gorm:"column:PCustomerOrderCode" json:"PCustomerOrderCode"`
	PInCode                 sql.NullString  `gorm:"column:PInCode" json:"PInCode"`
	POutCode                string          `gorm:"column:POutCode" json:"POutCode"`
	PQualityJudgeCode       sql.NullString  `gorm:"column:PQualityJudgeCode" json:"PQualityJudgeCode"`
	PQuotationCode          sql.NullString  `gorm:"column:PQuotationCode" json:"PQuotationCode"`
	PQuotationIndexID       sql.NullInt64   `gorm:"column:PQuotationIndexID" json:"PQuotationIndexID"`
	PYCode                  sql.NullString  `gorm:"column:PYCode" json:"PYCode"`
	PackQty                 sql.NullFloat64 `gorm:"column:PackQty" json:"PackQty"`
	PackUnit                sql.NullString  `gorm:"column:PackUnit" json:"PackUnit"`
	PackagePieceQty         sql.NullFloat64 `gorm:"column:PackagePieceQty" json:"PackagePieceQty"`
	PackageQty              sql.NullInt64   `gorm:"column:PackageQty" json:"PackageQty"`
	PartsIntegral           sql.NullFloat64 `gorm:"column:PartsIntegral" json:"PartsIntegral"`
	PrefPrice1              sql.NullFloat64 `gorm:"column:PrefPrice1" json:"PrefPrice1"`
	PrefPrice10             sql.NullFloat64 `gorm:"column:PrefPrice10" json:"PrefPrice10"`
	PrefPrice2              sql.NullFloat64 `gorm:"column:PrefPrice2" json:"PrefPrice2"`
	PrefPrice3              sql.NullFloat64 `gorm:"column:PrefPrice3" json:"PrefPrice3"`
	PrefPrice4              sql.NullFloat64 `gorm:"column:PrefPrice4" json:"PrefPrice4"`
	PrefPrice5              sql.NullFloat64 `gorm:"column:PrefPrice5" json:"PrefPrice5"`
	PrefPrice6              sql.NullFloat64 `gorm:"column:PrefPrice6" json:"PrefPrice6"`
	PrefPrice7              sql.NullFloat64 `gorm:"column:PrefPrice7" json:"PrefPrice7"`
	PrefPrice8              sql.NullFloat64 `gorm:"column:PrefPrice8" json:"PrefPrice8"`
	PrefPrice9              sql.NullFloat64 `gorm:"column:PrefPrice9" json:"PrefPrice9"`
	Price                   sql.NullFloat64 `gorm:"column:Price" json:"Price"`
	PriceType               sql.NullString  `gorm:"column:PriceType" json:"PriceType"`
	Qty                     sql.NullFloat64 `gorm:"column:Qty" json:"Qty"`
	RTDiscountRate          sql.NullFloat64 `gorm:"column:RTDiscountRate" json:"RTDiscountRate"`
	RecTypeD                sql.NullString  `gorm:"column:RecTypeD" json:"RecTypeD"`
	RefPrice1               sql.NullFloat64 `gorm:"column:RefPrice1" json:"RefPrice1"`
	RefPrice2               sql.NullFloat64 `gorm:"column:RefPrice2" json:"RefPrice2"`
	RefPrice3               sql.NullFloat64 `gorm:"column:RefPrice3" json:"RefPrice3"`
	RefPrice4               sql.NullFloat64 `gorm:"column:RefPrice4" json:"RefPrice4"`
	ReturnPriceProfitAmount sql.NullFloat64 `gorm:"column:ReturnPriceProfitAmount" json:"ReturnPriceProfitAmount"`
	ReturnQty               sql.NullFloat64 `gorm:"column:ReturnQty" json:"ReturnQty"`
	ReturnTypeD             sql.NullString  `gorm:"column:ReturnTypeD" json:"ReturnTypeD"`
	SalesLeader             sql.NullString  `gorm:"column:SalesLeader" json:"SalesLeader"`
	SalesLeaderCode         sql.NullString  `gorm:"column:SalesLeaderCode" json:"SalesLeaderCode"`
	SalesLeaderD            sql.NullString  `gorm:"column:SalesLeaderD" json:"SalesLeaderD"`
	SalesPromotionCode      sql.NullString  `gorm:"column:SalesPromotionCode" json:"SalesPromotionCode"`
	SourceOperatorCode      sql.NullString  `gorm:"column:SourceOperatorCode" json:"SourceOperatorCode"`
	SourceOperatorName      sql.NullString  `gorm:"column:SourceOperatorName" json:"SourceOperatorName"`
	SourceOutCode           sql.NullString  `gorm:"column:SourceOutCode" json:"SourceOutCode"`
	SourceOutDiscountRate   sql.NullFloat64 `gorm:"column:SourceOutDiscountRate" json:"SourceOutDiscountRate"`
	SourceOutFalsePrice     sql.NullFloat64 `gorm:"column:SourceOutFalsePrice" json:"SourceOutFalsePrice"`
	SourceOutIndexID        sql.NullInt64   `gorm:"column:SourceOutIndexID" json:"SourceOutIndexID"`
	SourceOutPrice          sql.NullFloat64 `gorm:"column:SourceOutPrice" json:"SourceOutPrice"`
	SourceOutQty            sql.NullFloat64 `gorm:"column:SourceOutQty" json:"SourceOutQty"`
	StandardPrice           sql.NullFloat64 `gorm:"column:StandardPrice" json:"StandardPrice"`
	StockID                 sql.NullString  `gorm:"column:StockID" json:"StockID"`
	StockSalesQty           sql.NullFloat64 `gorm:"column:StockSalesQty" json:"StockSalesQty"`
	SupplierCode            sql.NullString  `gorm:"column:SupplierCode" json:"SupplierCode"`
	SupplierName            sql.NullString  `gorm:"column:SupplierName" json:"SupplierName"`
	SupplyAmount            sql.NullFloat64 `gorm:"column:SupplyAmount" json:"SupplyAmount"`
	TmpField1               sql.NullString  `gorm:"column:TmpField1" json:"TmpField1"`
	TradePrice              sql.NullFloat64 `gorm:"column:TradePrice" json:"TradePrice"`
	TranInCode              sql.NullString  `gorm:"column:TranInCode" json:"TranInCode"`
	TranQty                 sql.NullFloat64 `gorm:"column:TranQty" json:"TranQty"`
	TransferPrice           sql.NullFloat64 `gorm:"column:TransferPrice" json:"TransferPrice"`
	UnStockID               sql.NullInt64   `gorm:"column:UnStockID" json:"UnStockID"`
	Unit                    sql.NullString  `gorm:"column:Unit" json:"Unit"`
	UserDefCode             sql.NullString  `gorm:"column:UserDefCode" json:"UserDefCode"`
	ValidDate               time.Time       `gorm:"column:ValidDate" json:"ValidDate"`
	Vol                     sql.NullFloat64 `gorm:"column:Vol" json:"Vol"`
	WBCode                  sql.NullString  `gorm:"column:WBCode" json:"WBCode"`
	Weight                  sql.NullFloat64 `gorm:"column:Weight" json:"Weight"`
	WorkType                sql.NullString  `gorm:"column:WorkType" json:"WorkType"`
	Attributecode           sql.NullString  `gorm:"column:attributecode" json:"attributecode"`
	Cid                     int             `gorm:"column:cid" json:"cid"`
	Class                   sql.NullString  `gorm:"column:class" json:"class"`
	ID                      int             `gorm:"column:id;primary_key" json:"id;primary_key"`
}

// TableName sets the insert table name for this struct type
func (p *POutd) TableName() string {
	return "p_outd"
}
