package models

import (
	"database/sql"
	"time"
)

type POutm struct {
	AccAppDate                   time.Time       `gorm:"column:AccAppDate" json:"AccAppDate"`
	AccAppPersonCode             sql.NullString  `gorm:"column:AccAppPersonCode" json:"AccAppPersonCode"`
	AccAppPersonName             sql.NullString  `gorm:"column:AccAppPersonName" json:"AccAppPersonName"`
	AccCardAmount                sql.NullFloat64 `gorm:"column:AccCardAmount" json:"AccCardAmount"`
	AccCashAmount                sql.NullFloat64 `gorm:"column:AccCashAmount" json:"AccCashAmount"`
	AccOtherAmount               sql.NullFloat64 `gorm:"column:AccOtherAmount" json:"AccOtherAmount"`
	AccType                      sql.NullString  `gorm:"column:AccType" json:"AccType"`
	AccountDate                  time.Time       `gorm:"column:AccountDate" json:"AccountDate"`
	AccountPersonCode            sql.NullString  `gorm:"column:AccountPersonCode" json:"AccountPersonCode"`
	AccountPersonName            sql.NullString  `gorm:"column:AccountPersonName" json:"AccountPersonName"`
	AccountRemarks               sql.NullString  `gorm:"column:AccountRemarks" json:"AccountRemarks"`
	ActPresentIntegral           sql.NullFloat64 `gorm:"column:ActPresentIntegral" json:"ActPresentIntegral"`
	Approval                     int             `gorm:"column:Approval" json:"Approval"`
	ApprovalDate                 time.Time       `gorm:"column:ApprovalDate" json:"ApprovalDate"`
	ApproverCode                 sql.NullString  `gorm:"column:ApproverCode" json:"ApproverCode"`
	ApproverName                 sql.NullString  `gorm:"column:ApproverName" json:"ApproverName"`
	ArrearAmount                 sql.NullFloat64 `gorm:"column:ArrearAmount" json:"ArrearAmount"`
	ArrearDiscountAmount         sql.NullFloat64 `gorm:"column:ArrearDiscountAmount" json:"ArrearDiscountAmount"`
	ArrearPreReceiveAmount       sql.NullFloat64 `gorm:"column:ArrearPreReceiveAmount" json:"ArrearPreReceiveAmount"`
	ArrearReceiveAmount          sql.NullFloat64 `gorm:"column:ArrearReceiveAmount" json:"ArrearReceiveAmount"`
	BHAmount                     sql.NullFloat64 `gorm:"column:BHAmount" json:"BHAmount"`
	BHDate                       time.Time       `gorm:"column:BHDate" json:"BHDate"`
	BHPayee                      sql.NullString  `gorm:"column:BHPayee" json:"BHPayee"`
	BHPercent                    sql.NullFloat64 `gorm:"column:BHPercent" json:"BHPercent"`
	BadDebtsAmount               sql.NullFloat64 `gorm:"column:BadDebtsAmount" json:"BadDebtsAmount"`
	BadDebtsDate                 time.Time       `gorm:"column:BadDebtsDate" json:"BadDebtsDate"`
	BadDebtsPersonCode           sql.NullString  `gorm:"column:BadDebtsPersonCode" json:"BadDebtsPersonCode"`
	BadDebtsPersonName           sql.NullString  `gorm:"column:BadDebtsPersonName" json:"BadDebtsPersonName"`
	BadDebtsReason               sql.NullString  `gorm:"column:BadDebtsReason" json:"BadDebtsReason"`
	BalanceAmount                sql.NullFloat64 `gorm:"column:BalanceAmount" json:"BalanceAmount"`
	BalanceIntegral              sql.NullFloat64 `gorm:"column:BalanceIntegral" json:"BalanceIntegral"`
	BalanceMemberIntegral        sql.NullFloat64 `gorm:"column:BalanceMemberIntegral" json:"BalanceMemberIntegral"`
	BalanceValueAmount           sql.NullFloat64 `gorm:"column:BalanceValueAmount" json:"BalanceValueAmount"`
	Bank                         sql.NullString  `gorm:"column:Bank" json:"Bank"`
	BankAccount                  sql.NullString  `gorm:"column:BankAccount" json:"BankAccount"`
	CModel                       sql.NullString  `gorm:"column:CModel" json:"CModel"`
	CPreReceiveAmount            sql.NullFloat64 `gorm:"column:CPreReceiveAmount" json:"CPreReceiveAmount"`
	CReceptionCode               sql.NullString  `gorm:"column:CReceptionCode" json:"CReceptionCode"`
	CalcPODate                   time.Time       `gorm:"column:CalcPODate" json:"CalcPODate"`
	CanIntegralAmount            sql.NullFloat64 `gorm:"column:CanIntegralAmount" json:"CanIntegralAmount"`
	CardSelect                   sql.NullString  `gorm:"column:CardSelect" json:"CardSelect"`
	CarryCode                    sql.NullString  `gorm:"column:CarryCode" json:"CarryCode"`
	CarryInvoiceNo               sql.NullString  `gorm:"column:CarryInvoiceNo" json:"CarryInvoiceNo"`
	CarryName                    sql.NullString  `gorm:"column:CarryName" json:"CarryName"`
	Charge1Amount                sql.NullFloat64 `gorm:"column:Charge1Amount" json:"Charge1Amount"`
	Charge2Amount                sql.NullFloat64 `gorm:"column:Charge2Amount" json:"Charge2Amount"`
	Charge3Amount                sql.NullFloat64 `gorm:"column:Charge3Amount" json:"Charge3Amount"`
	CheckerCode                  sql.NullString  `gorm:"column:CheckerCode" json:"CheckerCode"`
	CheckerName                  sql.NullString  `gorm:"column:CheckerName" json:"CheckerName"`
	Class                        sql.NullString  `gorm:"column:Class" json:"Class"`
	ComNo                        string          `gorm:"column:ComNo" json:"ComNo"`
	CustomerCode                 sql.NullString  `gorm:"column:CustomerCode" json:"CustomerCode"`
	CustomerName                 sql.NullString  `gorm:"column:CustomerName" json:"CustomerName"`
	DeliveryCompany              sql.NullString  `gorm:"column:DeliveryCompany" json:"DeliveryCompany"`
	DeliveryDate                 time.Time       `gorm:"column:DeliveryDate" json:"DeliveryDate"`
	DeliveryManCode              sql.NullString  `gorm:"column:DeliveryManCode" json:"DeliveryManCode"`
	DeliveryManName              sql.NullString  `gorm:"column:DeliveryManName" json:"DeliveryManName"`
	DeliveryRemarks              sql.NullString  `gorm:"column:DeliveryRemarks" json:"DeliveryRemarks"`
	Deliveryman                  sql.NullString  `gorm:"column:Deliveryman" json:"Deliveryman"`
	DepartmentM                  sql.NullString  `gorm:"column:DepartmentM" json:"DepartmentM"`
	DiscountAmount               sql.NullFloat64 `gorm:"column:DiscountAmount" json:"DiscountAmount"`
	DiscountRate                 sql.NullFloat64 `gorm:"column:DiscountRate" json:"DiscountRate"`
	Dispatcher                   sql.NullString  `gorm:"column:Dispatcher" json:"Dispatcher"`
	DisuseDate                   time.Time       `gorm:"column:DisuseDate" json:"DisuseDate"`
	DisuseReason                 sql.NullString  `gorm:"column:DisuseReason" json:"DisuseReason"`
	DocDate                      time.Time       `gorm:"column:DocDate" json:"DocDate"`
	Driver                       sql.NullString  `gorm:"column:Driver" json:"Driver"`
	FromFunctionCode             sql.NullString  `gorm:"column:FromFunctionCode" json:"FromFunctionCode"`
	FromOutCode                  sql.NullString  `gorm:"column:FromOutCode" json:"FromOutCode"`
	FunctionCode                 string          `gorm:"column:FunctionCode" json:"FunctionCode"`
	GoodsCount                   sql.NullInt64   `gorm:"column:GoodsCount" json:"GoodsCount"`
	HSalesCode                   sql.NullString  `gorm:"column:HSalesCode" json:"HSalesCode"`
	IntegralCardCode             sql.NullString  `gorm:"column:IntegralCardCode" json:"IntegralCardCode"`
	IntegralCardNo               sql.NullString  `gorm:"column:IntegralCardNo" json:"IntegralCardNo"`
	InvoiceDate                  time.Time       `gorm:"column:InvoiceDate" json:"InvoiceDate"`
	InvoiceNo                    sql.NullString  `gorm:"column:InvoiceNo" json:"InvoiceNo"`
	InvoiceType                  sql.NullString  `gorm:"column:InvoiceType" json:"InvoiceType"`
	IsAccApp                     sql.NullInt64   `gorm:"column:IsAccApp" json:"IsAccApp"`
	IsArrear                     sql.NullInt64   `gorm:"column:IsArrear" json:"IsArrear"`
	IsArrive                     sql.NullInt64   `gorm:"column:IsArrive" json:"IsArrive"`
	IsBadDebts                   sql.NullInt64   `gorm:"column:IsBadDebts" json:"IsBadDebts"`
	IsCommMoney                  sql.NullInt64   `gorm:"column:IsCommMoney" json:"IsCommMoney"`
	IsNeedDelivery               sql.NullInt64   `gorm:"column:IsNeedDelivery" json:"IsNeedDelivery"`
	IsTranComplete               sql.NullInt64   `gorm:"column:IsTranComplete" json:"IsTranComplete"`
	MemberCardNo                 sql.NullString  `gorm:"column:MemberCardNo" json:"MemberCardNo"`
	MemberCode                   sql.NullString  `gorm:"column:MemberCode" json:"MemberCode"`
	MemberType                   sql.NullString  `gorm:"column:MemberType" json:"MemberType"`
	MemberYears                  sql.NullInt64   `gorm:"column:MemberYears" json:"MemberYears"`
	ModifyDate                   time.Time       `gorm:"column:ModifyDate" json:"ModifyDate"`
	ModifyIP                     sql.NullString  `gorm:"column:ModifyIP" json:"ModifyIP"`
	ModifyPersonCode             sql.NullString  `gorm:"column:ModifyPersonCode" json:"ModifyPersonCode"`
	ModifyPersonName             sql.NullString  `gorm:"column:ModifyPersonName" json:"ModifyPersonName"`
	ModifyWorkStation            sql.NullString  `gorm:"column:ModifyWorkStation" json:"ModifyWorkStation"`
	MustDeliveryDate             time.Time       `gorm:"column:MustDeliveryDate" json:"MustDeliveryDate"`
	NeedVisitDate                time.Time       `gorm:"column:NeedVisitDate" json:"NeedVisitDate"`
	OperatorCode                 sql.NullString  `gorm:"column:OperatorCode" json:"OperatorCode"`
	OperatorName                 sql.NullString  `gorm:"column:OperatorName" json:"OperatorName"`
	Other1Amount                 sql.NullFloat64 `gorm:"column:Other1Amount" json:"Other1Amount"`
	Other2Amount                 sql.NullFloat64 `gorm:"column:Other2Amount" json:"Other2Amount"`
	Other3Amount                 sql.NullFloat64 `gorm:"column:Other3Amount" json:"Other3Amount"`
	OtherAccType                 sql.NullString  `gorm:"column:OtherAccType" json:"OtherAccType"`
	OtherAmount                  sql.NullFloat64 `gorm:"column:OtherAmount" json:"OtherAmount"`
	OutMFlag1                    sql.NullInt64   `gorm:"column:OutMFlag1" json:"OutMFlag1"`
	OutMFlag2                    sql.NullInt64   `gorm:"column:OutMFlag2" json:"OutMFlag2"`
	OutMFlag3                    sql.NullInt64   `gorm:"column:OutMFlag3" json:"OutMFlag3"`
	OutType                      sql.NullString  `gorm:"column:OutType" json:"OutType"`
	PBackHanderCode              sql.NullString  `gorm:"column:PBackHanderCode" json:"PBackHanderCode"`
	PManageAmount                sql.NullFloat64 `gorm:"column:PManageAmount" json:"PManageAmount"`
	PManageRate                  sql.NullFloat64 `gorm:"column:PManageRate" json:"PManageRate"`
	POutArriveDate               time.Time       `gorm:"column:POutArriveDate" json:"POutArriveDate"`
	POutCode                     string          `gorm:"column:POutCode" json:"POutCode"`
	PQuotationCode               sql.NullString  `gorm:"column:PQuotationCode" json:"PQuotationCode"`
	PReferAmount                 sql.NullFloat64 `gorm:"column:PReferAmount" json:"PReferAmount"`
	PReferDecAmount              sql.NullFloat64 `gorm:"column:PReferDecAmount" json:"PReferDecAmount"`
	PReferRate                   sql.NullFloat64 `gorm:"column:PReferRate" json:"PReferRate"`
	Packer                       sql.NullString  `gorm:"column:Packer" json:"Packer"`
	PakeLocation                 sql.NullString  `gorm:"column:PakeLocation" json:"PakeLocation"`
	PayRemarks                   sql.NullString  `gorm:"column:PayRemarks" json:"PayRemarks"`
	PreReceiveAmount             sql.NullFloat64 `gorm:"column:PreReceiveAmount" json:"PreReceiveAmount"`
	PresentIntegral              sql.NullFloat64 `gorm:"column:PresentIntegral" json:"PresentIntegral"`
	PrintCount                   sql.NullInt64   `gorm:"column:PrintCount" json:"PrintCount"`
	QuoMField1                   sql.NullString  `gorm:"column:QuoMField1" json:"QuoMField1"`
	QuoMField2                   sql.NullString  `gorm:"column:QuoMField2" json:"QuoMField2"`
	QuoMField3                   sql.NullString  `gorm:"column:QuoMField3" json:"QuoMField3"`
	QuoMField4                   sql.NullString  `gorm:"column:QuoMField4" json:"QuoMField4"`
	QuoMField5                   sql.NullString  `gorm:"column:QuoMField5" json:"QuoMField5"`
	QuoMField6                   sql.NullString  `gorm:"column:QuoMField6" json:"QuoMField6"`
	QuoMField7                   sql.NullString  `gorm:"column:QuoMField7" json:"QuoMField7"`
	QuoMField8                   sql.NullString  `gorm:"column:QuoMField8" json:"QuoMField8"`
	RecPersonCode                sql.NullString  `gorm:"column:RecPersonCode" json:"RecPersonCode"`
	RecPersonName                sql.NullString  `gorm:"column:RecPersonName" json:"RecPersonName"`
	RecType                      sql.NullString  `gorm:"column:RecType" json:"RecType"`
	ReceivableAmount             sql.NullFloat64 `gorm:"column:ReceivableAmount" json:"ReceivableAmount"`
	ReceivableFalseAmount        sql.NullFloat64 `gorm:"column:ReceivableFalseAmount" json:"ReceivableFalseAmount"`
	ReceiveAmount                sql.NullFloat64 `gorm:"column:ReceiveAmount" json:"ReceiveAmount"`
	Receiver                     sql.NullString  `gorm:"column:Receiver" json:"Receiver"`
	RegisterNo                   sql.NullString  `gorm:"column:RegisterNo" json:"RegisterNo"`
	Remarks                      sql.NullString  `gorm:"column:Remarks" json:"Remarks"`
	ReturnReason                 sql.NullString  `gorm:"column:ReturnReason" json:"ReturnReason"`
	ReturnType                   sql.NullString  `gorm:"column:ReturnType" json:"ReturnType"`
	SalesLeader                  sql.NullString  `gorm:"column:SalesLeader" json:"SalesLeader"`
	SalesmanCode                 sql.NullString  `gorm:"column:SalesmanCode" json:"SalesmanCode"`
	SalesmanName                 sql.NullString  `gorm:"column:SalesmanName" json:"SalesmanName"`
	SendPeriod                   sql.NullInt64   `gorm:"column:SendPeriod" json:"SendPeriod"`
	Status                       int             `gorm:"column:Status" json:"Status"`
	TakerCode                    sql.NullString  `gorm:"column:TakerCode" json:"TakerCode"`
	TakerName                    sql.NullString  `gorm:"column:TakerName" json:"TakerName"`
	TaxAmount                    sql.NullFloat64 `gorm:"column:TaxAmount" json:"TaxAmount"`
	TaxRate                      sql.NullFloat64 `gorm:"column:TaxRate" json:"TaxRate"`
	ToOutCode                    sql.NullString  `gorm:"column:ToOutCode" json:"ToOutCode"`
	TotalBonusAmount             sql.NullFloat64 `gorm:"column:TotalBonusAmount" json:"TotalBonusAmount"`
	TotalBoxes                   sql.NullInt64   `gorm:"column:TotalBoxes" json:"TotalBoxes"`
	TotalCostAmount              sql.NullFloat64 `gorm:"column:TotalCostAmount" json:"TotalCostAmount"`
	TotalCount                   sql.NullInt64   `gorm:"column:TotalCount" json:"TotalCount"`
	TotalDiscountAmount          sql.NullFloat64 `gorm:"column:TotalDiscountAmount" json:"TotalDiscountAmount"`
	TotalFalsePriceAmount        sql.NullFloat64 `gorm:"column:TotalFalsePriceAmount" json:"TotalFalsePriceAmount"`
	TotalNoTaxCostAmount         sql.NullFloat64 `gorm:"column:TotalNoTaxCostAmount" json:"TotalNoTaxCostAmount"`
	TotalPartsIntegral           sql.NullFloat64 `gorm:"column:TotalPartsIntegral" json:"TotalPartsIntegral"`
	TotalPresentAmount           sql.NullFloat64 `gorm:"column:TotalPresentAmount" json:"TotalPresentAmount"`
	TotalPriceAmount             sql.NullFloat64 `gorm:"column:TotalPriceAmount" json:"TotalPriceAmount"`
	TotalQty                     sql.NullFloat64 `gorm:"column:TotalQty" json:"TotalQty"`
	TotalRefAmount               sql.NullFloat64 `gorm:"column:TotalRefAmount" json:"TotalRefAmount"`
	TotalReturnPriceProfitAmount sql.NullFloat64 `gorm:"column:TotalReturnPriceProfitAmount" json:"TotalReturnPriceProfitAmount"`
	TotalSumAmount               sql.NullFloat64 `gorm:"column:TotalSumAmount" json:"TotalSumAmount"`
	TotalSumFalseAmount          sql.NullFloat64 `gorm:"column:TotalSumFalseAmount" json:"TotalSumFalseAmount"`
	TotalType                    sql.NullInt64   `gorm:"column:TotalType" json:"TotalType"`
	TotalVol                     sql.NullFloat64 `gorm:"column:TotalVol" json:"TotalVol"`
	TotalWeight                  sql.NullFloat64 `gorm:"column:TotalWeight" json:"TotalWeight"`
	TransCarryAmount             float64         `gorm:"column:TransCarryAmount" json:"TransCarryAmount"`
	TransCustomerAmount          float64         `gorm:"column:TransCustomerAmount" json:"TransCustomerAmount"`
	Transport                    sql.NullString  `gorm:"column:Transport" json:"Transport"`
	UseIntegral                  sql.NullFloat64 `gorm:"column:UseIntegral" json:"UseIntegral"`
	ValueCardNo                  sql.NullString  `gorm:"column:ValueCardNo" json:"ValueCardNo"`
	VehicleCode                  sql.NullString  `gorm:"column:VehicleCode" json:"VehicleCode"`
	Vin                          sql.NullString  `gorm:"column:Vin" json:"Vin"`
	WorkAmount                   sql.NullFloat64 `gorm:"column:WorkAmount" json:"WorkAmount"`
	Cid                          int             `gorm:"column:cid" json:"cid"`
	ID                           int             `gorm:"column:id;primary_key" json:"id;primary_key"`
	Pickingtype                  int             `gorm:"column:pickingtype" json:"pickingtype"`
}

// TableName sets the insert table name for this struct type
func (p *POutm) TableName() string {
	return "p_outm"
}
